version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  messaging-service:
    build: ./messaging-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
